services:
  - type: web
    name: pitch-super-app-backend
    env: python
    buildCommand: ""
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: LINKEDIN_USER
        sync: false
      - key: LINKEDIN_PASS
        sync: false 